audio = []
description = "I've read numerous articles about saving keystrokes.
The author counts the number of minutes you could save a day by doing a keyboard shortcut
and tell you how many hours (or days) you could save in a year.
This focus on efficiency didn't resonate with me.
I never thought my main bottleneck as a developer was using a mouse or needing to type a few extra characters. "
images = []
series = []
tags = []
title = "Finding Flow in Your Dev Environment"
video = []
